# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/fifo_generator_Width28_Depth16_DistRAM/fifo_generator_Width28_Depth16_DistRAM.xci
# IP: The module: 'fifo_generator_Width28_Depth16_DistRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/fifo_generator_Width28_Depth16_DistRAM/fifo_generator_Width28_Depth16_DistRAM/fifo_generator_Width28_Depth16_DistRAM.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_Width28_Depth16_DistRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/fifo_generator_Width28_Depth16_DistRAM/fifo_generator_Width28_Depth16_DistRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_Width28_Depth16_DistRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/fifo_generator_Width28_Depth16_DistRAM/fifo_generator_Width28_Depth16_DistRAM.xci
# IP: The module: 'fifo_generator_Width28_Depth16_DistRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/fifo_generator_Width28_Depth16_DistRAM/fifo_generator_Width28_Depth16_DistRAM/fifo_generator_Width28_Depth16_DistRAM.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_Width28_Depth16_DistRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/fifo_generator_Width28_Depth16_DistRAM/fifo_generator_Width28_Depth16_DistRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_Width28_Depth16_DistRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
