# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.cache/wt [current_project]
set_property parent.project_path /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/xbip_dsp48_macro_A18_B18_P48_NoRounding_synth_1/xbip_dsp48_macro_A18_B18_P48_NoRounding.dcp
set_property used_in_implementation false [get_files /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/xbip_dsp48_macro_A18_B18_P48_NoRounding_synth_1/xbip_dsp48_macro_A18_B18_P48_NoRounding.dcp]
add_files -quiet /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/blk_mem_gen_TDP_Awrite288read288depth16384_BsimilarToA_128BRAM_synth_1/blk_mem_gen_TDP_Awrite288read288depth16384_BsimilarToA_128BRAM.dcp
set_property used_in_implementation false [get_files /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/blk_mem_gen_TDP_Awrite288read288depth16384_BsimilarToA_128BRAM_synth_1/blk_mem_gen_TDP_Awrite288read288depth16384_BsimilarToA_128BRAM.dcp]
read_vhdl -library xil_defaultlib {
  /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/new/GlobalPackage.vhd
  /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/new/TestPackage.vhd
  /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/new/Test.vhd
}
read_xdc /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/constrs_1/new/StreamWriteControl.xdc
set_property used_in_implementation false [get_files /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/constrs_1/new/StreamWriteControl.xdc]

synth_design -top Test -part xc7vx485tffg1761-2 -mode out_of_context
write_checkpoint -noxdef Test.dcp
catch { report_utilization -file Test_utilization_synth.rpt -pb Test_utilization_synth.pb }
