# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/xbip_dsp48_macro_A18_B18_P48_NoRounding/xbip_dsp48_macro_A18_B18_P48_NoRounding.xci
# IP: The module: 'xbip_dsp48_macro_A18_B18_P48_NoRounding' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/xbip_dsp48_macro_A18_B18_P48_NoRounding/xbip_dsp48_macro_A18_B18_P48_NoRounding_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_dsp48_macro_A18_B18_P48_NoRounding'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/xbip_dsp48_macro_A18_B18_P48_NoRounding/xbip_dsp48_macro_A18_B18_P48_NoRounding.xci
# IP: The module: 'xbip_dsp48_macro_A18_B18_P48_NoRounding' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/xbip_dsp48_macro_A18_B18_P48_NoRounding/xbip_dsp48_macro_A18_B18_P48_NoRounding_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_dsp48_macro_A18_B18_P48_NoRounding'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
