# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/blk_mem_gen_SDP_Awrite144depth256_Bread144/blk_mem_gen_SDP_Awrite144depth256_Bread144.xci
# IP: The module: 'blk_mem_gen_SDP_Awrite144depth256_Bread144' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/blk_mem_gen_SDP_Awrite144depth256_Bread144/blk_mem_gen_SDP_Awrite144depth256_Bread144_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_SDP_Awrite144depth256_Bread144'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/blk_mem_gen_SDP_Awrite144depth256_Bread144/blk_mem_gen_SDP_Awrite144depth256_Bread144.xci
# IP: The module: 'blk_mem_gen_SDP_Awrite144depth256_Bread144' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/ip/blk_mem_gen_SDP_Awrite144depth256_Bread144/blk_mem_gen_SDP_Awrite144depth256_Bread144_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_SDP_Awrite144depth256_Bread144'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
