# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.cache/wt [current_project]
set_property parent.project_path /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/fifo_generator_Width160_Depth512_synth_1/fifo_generator_Width160_Depth512.dcp
set_property used_in_implementation false [get_files /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/fifo_generator_Width160_Depth512_synth_1/fifo_generator_Width160_Depth512.dcp]
add_files -quiet /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/fifo_generator_Width320_Depth16_DistRAM_synth_1/fifo_generator_Width320_Depth16_DistRAM.dcp
set_property used_in_implementation false [get_files /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/fifo_generator_Width320_Depth16_DistRAM_synth_1/fifo_generator_Width320_Depth16_DistRAM.dcp]
add_files -quiet /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/fifo_generator_Width16_Depth16_DistRAM_synth_1/fifo_generator_Width16_Depth16_DistRAM.dcp
set_property used_in_implementation false [get_files /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/fifo_generator_Width16_Depth16_DistRAM_synth_1/fifo_generator_Width16_Depth16_DistRAM.dcp]
add_files -quiet /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/fifo_generator_Width480_Depth16_DistRAM_synth_1/fifo_generator_Width480_Depth16_DistRAM.dcp
set_property used_in_implementation false [get_files /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/fifo_generator_Width480_Depth16_DistRAM_synth_1/fifo_generator_Width480_Depth16_DistRAM.dcp]
add_files -quiet /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/fifo_generator_Width28_Depth16_DistRAM_synth_1/fifo_generator_Width28_Depth16_DistRAM.dcp
set_property used_in_implementation false [get_files /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.runs/fifo_generator_Width28_Depth16_DistRAM_synth_1/fifo_generator_Width28_Depth16_DistRAM.dcp]
read_vhdl -library xil_defaultlib {
  /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/new/GlobalPackage.vhd
  /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/new/WeightBankPkg.vhd
  /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/new/ConvPackage.vhd
  /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/new/ConvEngineDataBankPkg.vhd
  /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/new/ConvEngineOutput_Datapath_Alternate.vhd
  /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/new/ConvEngineOutput_Control_Level1_DDR.vhd
  /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/new/ConvEngineOutput_Control_Level1_DataBank.vhd
  /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/new/ConvEngineOutput_Control.vhd
  /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/sources_1/new/ConvEngineOutput_Top.vhd
}
read_xdc /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/constrs_1/new/StreamWriteControl.xdc
set_property used_in_implementation false [get_files /home/edcn103/Dropbox/M.tech/Project/Hardware_Implementation/ConvEngine/ConvEngine.srcs/constrs_1/new/StreamWriteControl.xdc]

synth_design -top ConvEngineOutput_Top -part xc7vx485tffg1761-2 -mode out_of_context
write_checkpoint -noxdef ConvEngineOutput_Top.dcp
catch { report_utilization -file ConvEngineOutput_Top_utilization_synth.rpt -pb ConvEngineOutput_Top_utilization_synth.pb }
